### ISSUE TITLE
Private gist option publishes to public gists

### ISSUE THREAD

**Issue by johntdyer** [drnic/github-tmbundle#18]
The title pretty much says it all, I am using the latest build and am not really sure where to start troubleshooting this one... Any suggestions ?

**Comment by adamvduke** [comment]
I was able to get it working by changing the name of the private gist button and value. See https://github.com/drnic/github-tmbundle/pull/19

**Comment by javan** [comment]
I had the same problem. @adamvduke's [patch](https://github.com/adamvduke/github-tmbundle/commit/4b3daf937ce835e09428c15ef1276de09f42c1c3) fixed it for me.

**Comment by johntdyer** [comment]
Cool, I'll close this out
