### ISSUE TITLE
Report activate error

### ISSUE THREAD

**Issue by clepore** [drnic/github-tmbundle#20]
I keep getting a 
"/system/library/frameworks/ruby.framework/Versions1.8/usr/lib/ruby/1.8/rubygems.rb:777:in 'report_activate_error': Could not find rubygem git (>=1.0.0) (Gem::LoadError)..." every time I try to use "show in github." I have installed the github gem and everything is up to date. I am also running Lion with rails 1.9.2. Error: https://img.skitch.com/20111115-c57x282w4xmgx8bxrd9tdws12x.jpg

Any ideas?

**Comment by normally-andrew** [comment]
Did you find a solution to this? I'm getting the same error, cannot find a way around it.

**Comment by clepore** [comment]
Using rvm, I switched my rails version to my default and installed the gem there. Then I switched back and everything worked like a charm. Good luck!
